pins = """
..... .x..x
..... .....
..... .....
"""

[defaults]
language = "english"
trigram_precision = 1000
keyboard_type = "ansi angle"

[weights]
heatmap = 1.8
fspeed = 23.0
lateral_penalty = 1.0
dsfb_ratio = 0.11
scissors = 4.5
lsbs = 2.2
inrolls = 2.9
outrolls = 1.35
onehands = 1.3
alternates = 0.4
alternates_sfs = 0.6
redirects = 12.4
redirects_sfs = 13.2
bad_redirects = 17.5
bad_redirects_sfs = 19.0
pinky_ring_bigrams = 0.2

[weights.max_finger_use]
penalty = 2.5
pinky = 9.0
ring = 14.0
middle = 20.0
index = 20.0
